import requests
from bs4 import BeautifulSoup
import time
import urllib.request
import sys

target_url = 'https://ja.wikipedia.org/wiki/%E5%9B%BD%E3%81%AE%E4%B8%80%E8%A6%A7?cid=eu_hb_hva_mb_B-20472-122141149-001-001'
#requestsを使って、webから取得
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'}
r = requests.get(target_url, headers=headers)
print(r.text)
soup = BeautifulSoup(r.text, 'lxml')

# 下記の値を取得する
# div.topicsfb で抽出　更に aタグで抽出
wikitable = soup.find("table",class_="wikitable")
td = wikitable.find_all("td")

cnt = 0
for str in td :
    cnt += 1
    if cnt % 2 == 0 :
        a = str.find("a")
        print(a.get("href"))

def download(url,title):
    # エンコードしたタイトルを末尾にくっつける
    url = url + urllib.parse.quote_plus(title, encoding='utf-8')
    # タイトルを組み合わせURLを生成しダウンロードを行う。
    urllib.request.urlretrieve(url,f"./data/wikipedia/{title}.html")
#     ダウンロードしたら1秒待つ
    time.sleep(1)

if __name__ == "__main__":
    download("https://ja.wikipedia.org/wiki/","アイスランド")
    download("https://ja.wikipedia.org/wiki/","アイルランド")
    download("https://ja.wikipedia.org/wiki/","アゼルバイジャン")
    download("https://ja.wikipedia.org/wiki/","アフガニスタン")
    download("https://ja.wikipedia.org/wiki/","アメリカ合衆国")
    download("https://ja.wikipedia.org/wiki/","アラブ首長国連邦")
    download("https://ja.wikipedia.org/wiki/","アルジェリア")
    download("https://ja.wikipedia.org/wiki/","アルゼンチン")
    download("https://ja.wikipedia.org/wiki/","アルバニア")
    download("https://ja.wikipedia.org/wiki/","アルメニア")
    download("https://ja.wikipedia.org/wiki/","アンゴラ")
    download("https://ja.wikipedia.org/wiki/","アンティグア・バーブーダ")
    download("https://ja.wikipedia.org/wiki/","アンドラ")
    download("https://ja.wikipedia.org/wiki/","イエメン")
    download("https://ja.wikipedia.org/wiki/","イギリス")
    download("https://ja.wikipedia.org/wiki/","イスラエル")
    download("https://ja.wikipedia.org/wiki/","イタリア")
    download("https://ja.wikipedia.org/wiki/","イラク")
    download("https://ja.wikipedia.org/wiki/","イラン")
    download("https://ja.wikipedia.org/wiki/","インド")
    download("https://ja.wikipedia.org/wiki/","インドネシア")
    download("https://ja.wikipedia.org/wiki/","ウガンダ")
    download("https://ja.wikipedia.org/wiki/","ウクライナ")
    download("https://ja.wikipedia.org/wiki/","ウズベキスタン")
    download("https://ja.wikipedia.org/wiki/","ウルグアイ")
    download("https://ja.wikipedia.org/wiki/","エクアドル")
    download("https://ja.wikipedia.org/wiki/","エジプト")
    download("https://ja.wikipedia.org/wiki/","エストニア")
    download("https://ja.wikipedia.org/wiki/","エスワティニ")
    download("https://ja.wikipedia.org/wiki/","エチオピア")
    download("https://ja.wikipedia.org/wiki/","エリトリア")
    download("https://ja.wikipedia.org/wiki/","エルサルバドル")
    download("https://ja.wikipedia.org/wiki/","オマーン")
    download("https://ja.wikipedia.org/wiki/","オランダ")
    download("https://ja.wikipedia.org/wiki/","オーストラリア")
    download("https://ja.wikipedia.org/wiki/","オーストリア")
    download("https://ja.wikipedia.org/wiki/","カザフスタン")
    download("https://ja.wikipedia.org/wiki/","カタール")
    download("https://ja.wikipedia.org/wiki/","カナダ")
    download("https://ja.wikipedia.org/wiki/","カメルーン")
    download("https://ja.wikipedia.org/wiki/","カンボジア")
    download("https://ja.wikipedia.org/wiki/","カーボベルデ")
    download("https://ja.wikipedia.org/wiki/","ガイアナ")
    download("https://ja.wikipedia.org/wiki/","ガボン")
    download("https://ja.wikipedia.org/wiki/","ガンビア")
    download("https://ja.wikipedia.org/wiki/","ガーナ")
    download("https://ja.wikipedia.org/wiki/","キプロス")
    download("https://ja.wikipedia.org/wiki/","キューバ")
    download("https://ja.wikipedia.org/wiki/","キリバス")
    download("https://ja.wikipedia.org/wiki/","キルギス")
    download("https://ja.wikipedia.org/wiki/","ギニア")
    download("https://ja.wikipedia.org/wiki/","ギニアビサウ")
    download("https://ja.wikipedia.org/wiki/","ギリシャ")
    download("https://ja.wikipedia.org/wiki/","クウェート")
    download("https://ja.wikipedia.org/wiki/","クロアチア")
    download("https://ja.wikipedia.org/wiki/","グアテマラ")
    download("https://ja.wikipedia.org/wiki/","グレナダ")
    download("https://ja.wikipedia.org/wiki/","ケニア")
    download("https://ja.wikipedia.org/wiki/","コスタリカ")
    download("https://ja.wikipedia.org/wiki/","コモロ")
    download("https://ja.wikipedia.org/wiki/","コロンビア")
    download("https://ja.wikipedia.org/wiki/","コンゴ共和国")
    download("https://ja.wikipedia.org/wiki/","コンゴ民主共和国")
    download("https://ja.wikipedia.org/wiki/","コートジボワール")
    download("https://ja.wikipedia.org/wiki/","サウジアラビア")
    download("https://ja.wikipedia.org/wiki/","サモア")
    download("https://ja.wikipedia.org/wiki/","サントメ・プリンシペ")
    download("https://ja.wikipedia.org/wiki/","サンマリノ")
    download("https://ja.wikipedia.org/wiki/","ザンビア")
    download("https://ja.wikipedia.org/wiki/","シエラレオネ")
    download("https://ja.wikipedia.org/wiki/","シリア")
    download("https://ja.wikipedia.org/wiki/","シンガポール")
    download("https://ja.wikipedia.org/wiki/","ジブチ")
    download("https://ja.wikipedia.org/wiki/","ジャマイカ")
    download("https://ja.wikipedia.org/wiki/","ジョージア_(国)")
    download("https://ja.wikipedia.org/wiki/","ジンバブエ")
    download("https://ja.wikipedia.org/wiki/","スイス")
    download("https://ja.wikipedia.org/wiki/","スウェーデン")
    download("https://ja.wikipedia.org/wiki/","スペイン")
    download("https://ja.wikipedia.org/wiki/","スリナム")
    download("https://ja.wikipedia.org/wiki/","スリランカ")
    download("https://ja.wikipedia.org/wiki/","スロバキア")
    download("https://ja.wikipedia.org/wiki/","スロベニア")
    download("https://ja.wikipedia.org/wiki/","スーダン")
    download("https://ja.wikipedia.org/wiki/","セネガル")
    download("https://ja.wikipedia.org/wiki/","セルビア")
    download("https://ja.wikipedia.org/wiki/","セントクリストファー・ネイビス")
    download("https://ja.wikipedia.org/wiki/","セントビンセント・グレナディーン")
    download("https://ja.wikipedia.org/wiki/","セントルシア")
    download("https://ja.wikipedia.org/wiki/","セーシェル")
    download("https://ja.wikipedia.org/wiki/","ソマリア")
    download("https://ja.wikipedia.org/wiki/","ソロモン諸島")
    download("https://ja.wikipedia.org/wiki/","タイ王国")
    download("https://ja.wikipedia.org/wiki/","タジキスタン")
    download("https://ja.wikipedia.org/wiki/","タンザニア")
    download("https://ja.wikipedia.org/wiki/","チェコ")
    download("https://ja.wikipedia.org/wiki/","チャド")
    download("https://ja.wikipedia.org/wiki/","チュニジア")
    download("https://ja.wikipedia.org/wiki/","チリ")
    download("https://ja.wikipedia.org/wiki/","ツバル")
    download("https://ja.wikipedia.org/wiki/","デンマーク")
    download("https://ja.wikipedia.org/wiki/","トリニダード・トバゴ")
    download("https://ja.wikipedia.org/wiki/","トルクメニスタン")
    download("https://ja.wikipedia.org/wiki/","トルコ")
    download("https://ja.wikipedia.org/wiki/","トンガ")
    download("https://ja.wikipedia.org/wiki/","トーゴ")
    download("https://ja.wikipedia.org/wiki/","ドイツ")
    download("https://ja.wikipedia.org/wiki/","ドミニカ共和国")
    download("https://ja.wikipedia.org/wiki/","ドミニカ国")
    download("https://ja.wikipedia.org/wiki/","ナイジェリア")
    download("https://ja.wikipedia.org/wiki/","ナウル")
    download("https://ja.wikipedia.org/wiki/","ナミビア")
    download("https://ja.wikipedia.org/wiki/","ニカラグア")
    download("https://ja.wikipedia.org/wiki/","ニジェール")
    download("https://ja.wikipedia.org/wiki/","ニュージーランド")
    download("https://ja.wikipedia.org/wiki/","ニーノシュク")
    download("https://ja.wikipedia.org/wiki/","ネパール")
    download("https://ja.wikipedia.org/wiki/","ノルウェー")
    download("https://ja.wikipedia.org/wiki/","ハイチ")
    download("https://ja.wikipedia.org/wiki/","ハンガリー")
    download("https://ja.wikipedia.org/wiki/","バヌアツ")
    download("https://ja.wikipedia.org/wiki/","バハマ")
    download("https://ja.wikipedia.org/wiki/","バルバドス")
    download("https://ja.wikipedia.org/wiki/","バングラデシュ")
    download("https://ja.wikipedia.org/wiki/","バーレーン")
    download("https://ja.wikipedia.org/wiki/","パキスタン")
    download("https://ja.wikipedia.org/wiki/","パナマ")
    download("https://ja.wikipedia.org/wiki/","パプアニューギニア")
    download("https://ja.wikipedia.org/wiki/","パラオ")
    download("https://ja.wikipedia.org/wiki/","パラグアイ")
    download("https://ja.wikipedia.org/wiki/","フィジー")
    download("https://ja.wikipedia.org/wiki/","フィリピン")
    download("https://ja.wikipedia.org/wiki/","フィンランド")
    download("https://ja.wikipedia.org/wiki/","フランス")
    download("https://ja.wikipedia.org/wiki/","ブラジル")
    download("https://ja.wikipedia.org/wiki/","ブルガリア")
    download("https://ja.wikipedia.org/wiki/","ブルキナファソ")
    download("https://ja.wikipedia.org/wiki/","ブルネイ")
    download("https://ja.wikipedia.org/wiki/","ブルンジ")
    download("https://ja.wikipedia.org/wiki/","ブークモール")
    download("https://ja.wikipedia.org/wiki/","ブータン")
    download("https://ja.wikipedia.org/wiki/","ベトナム")
    download("https://ja.wikipedia.org/wiki/","ベナン")
    download("https://ja.wikipedia.org/wiki/","ベネズエラ")
    download("https://ja.wikipedia.org/wiki/","ベラルーシ")
    download("https://ja.wikipedia.org/wiki/","ベリーズ")
    download("https://ja.wikipedia.org/wiki/","ベルギー")
    download("https://ja.wikipedia.org/wiki/","ペルー")
    download("https://ja.wikipedia.org/wiki/","ホンジュラス")
    download("https://ja.wikipedia.org/wiki/","ボスニア・ヘルツェゴビナ")
    download("https://ja.wikipedia.org/wiki/","ボツワナ")
    download("https://ja.wikipedia.org/wiki/","ボリビア")
    download("https://ja.wikipedia.org/wiki/","ポルトガル")
    download("https://ja.wikipedia.org/wiki/","ポーランド")
    download("https://ja.wikipedia.org/wiki/","マダガスカル")
    download("https://ja.wikipedia.org/wiki/","マッキューン＝ライシャワー式")
    download("https://ja.wikipedia.org/wiki/","マラウイ")
    download("https://ja.wikipedia.org/wiki/","マリ共和国")
    download("https://ja.wikipedia.org/wiki/","マルタ")
    download("https://ja.wikipedia.org/wiki/","マレーシア")
    download("https://ja.wikipedia.org/wiki/","マーシャル諸島")
    download("https://ja.wikipedia.org/wiki/","ミクロネシア連邦")
    download("https://ja.wikipedia.org/wiki/","ミャンマー")
    download("https://ja.wikipedia.org/wiki/","メキシコ")
    download("https://ja.wikipedia.org/wiki/","モザンビーク")
    download("https://ja.wikipedia.org/wiki/","モナコ")
    download("https://ja.wikipedia.org/wiki/","モルディブ")
    download("https://ja.wikipedia.org/wiki/","モルドバ")
    download("https://ja.wikipedia.org/wiki/","モロッコ")
    download("https://ja.wikipedia.org/wiki/","モンゴル国")
    download("https://ja.wikipedia.org/wiki/","モンテネグロ")
    download("https://ja.wikipedia.org/wiki/","モーリシャス")
    download("https://ja.wikipedia.org/wiki/","モーリタニア")
    download("https://ja.wikipedia.org/wiki/","ヨルダン")
    download("https://ja.wikipedia.org/wiki/","ラオス")
    download("https://ja.wikipedia.org/wiki/","ラトビア")
    download("https://ja.wikipedia.org/wiki/","リトアニア")
    download("https://ja.wikipedia.org/wiki/","リヒテンシュタイン")
    download("https://ja.wikipedia.org/wiki/","リビア")
    download("https://ja.wikipedia.org/wiki/","リベリア")
    download("https://ja.wikipedia.org/wiki/","ルクセンブルク")
    download("https://ja.wikipedia.org/wiki/","ルワンダ")
    download("https://ja.wikipedia.org/wiki/","ルーマニア")
    download("https://ja.wikipedia.org/wiki/","レソト")
    download("https://ja.wikipedia.org/wiki/","レバノン")
    download("https://ja.wikipedia.org/wiki/","ロシア")
    download("https://ja.wikipedia.org/wiki/","ワイリー方式")
    download("https://ja.wikipedia.org/wiki/","中央アフリカ共和国")
    download("https://ja.wikipedia.org/wiki/","中華人民共和国")
    download("https://ja.wikipedia.org/wiki/","北マケドニア")
    download("https://ja.wikipedia.org/wiki/","南アフリカ共和国")
    download("https://ja.wikipedia.org/wiki/","南スーダン")
    download("https://ja.wikipedia.org/wiki/","大韓民国")
    download("https://ja.wikipedia.org/wiki/","日本")
    download("https://ja.wikipedia.org/wiki/","朝鮮民主主義人民共和国")
    download("https://ja.wikipedia.org/wiki/","東ティモール")
    download("https://ja.wikipedia.org/wiki/","赤道ギニア")

# HTTPError: HTTP Error 404: Not FoundはURLが存在しませんの意味
